server:
  port: 0
spring:
  application:
    name: keycloak-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://stage.padotec.com.br:8080/auth/realms/padotec/protocol/openid-connect/certs
          #jwt.issuer-uri : http://localhost:8080/auth/realms/ms-users/
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
  data:
    mongodb:
      host: localhost
      port: 27017
      database: padoteclocks
      username: root
      password: MongoDB2020!
      authentication-database: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

